<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientOpsPortal.Application\ClientOpsPortal.Application.csproj" />
    <ProjectReference Include="..\ClientOpsPortal.Domain\ClientOpsPortal.Domain.csproj" />
    <ProjectReference Include="..\ClientOpsPortal.Infrastructure\ClientOpsPortal.Infrastructure.csproj" />
    <ProjectReference Include="..\..\services-directory\ClientOpsPortal.Services.Directory.Client\ClientOpsPortal.Services.Directory.Client.csproj" />
    <ProjectReference Include="..\..\auth\ClientOpsPortal.Services.Auth.Client\ClientOpsPortal.Services.Auth.Client.csproj" />
  </ItemGroup>
</Project>