<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\ClientOpsPortal.Contracts\ClientOpsPortal.Contracts.csproj" />
    <ProjectReference Include="..\ClientOpsPortal.Domain\ClientOpsPortal.Domain.csproj" />
    <ProjectReference Include="..\..\auth\ClientOpsPortal.Services.Auth.Client\ClientOpsPortal.Services.Auth.Client.csproj" />
    <ProjectReference Include="..\..\services-directory\ClientOpsPortal.Services.Directory.Contracts\ClientOpsPortal.Services.Directory.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\notifications\ClientOpsPortal.Services.Notifications.Client\ClientOpsPortal.Services.Notifications.Client.csproj" />
  </ItemGroup>
</Project>